export class OnOrbitDetails{
    id: string;
    idOnOrbit: string;
    classificationMarking: string;
    vismag: number;
    vismagMin: number;
    vismagMax: number;
    vismagMean: number;
    rcs: number;
    rcsMin: number;
    rcsMax: number;
    rcsMean: number;
    maxDeltaV: number;
    estDeltaVDuration: number;
    geoSlot: number;
    driftRate: number;
    dryMass: number;
    additionalMass: number;
    launchMass: number;
    bolFuelMass: number;
    solarArrayArea: number;
    fuelRemaining: number;
    source: string;
    dataMode: string;
    createdAt: string;
    createdBy: string;
    updatedAt: string;
    updatedBy: string
  }